#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 9000'
alias v='vim .'
alias yolo='git push origin master && git push heroku master'
alias dot='~/.dotfiles'
alias desk='~/Desktop'
alias kiba='~/.KIBA'
alias robocode='sh ~/robocode/robocode.sh'
alias del='rm -rf'
alias html='atom . && open index.html'
alias newhtml='mkdir css js && touch index.html css/style.css js/main.js'
alias npmsetup='mkdir public public/css views && touch server.js public/css/style.css && npm init && npm install express nodemon --save && subl .'
alias npmpack='npm install mustache mustache-express body-parser express-validator express-session --save'
alias npmall='npmsetup && npmpack'
alias ownbrew='sudo chown -R $(whoami) /usr/local'
alias py='python3'
alias pytest='python -m pytest'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"
alias gitown="git config --global github.user 'bricerb' && git config --global user.name 'Brice Blanch' && git config --global user.email 'bricerb@gmail.com'"
alias gitinc="git config --global github.user 'rblanch-incomm' && git config --global user.name 'rblanch-incomm' && git config --global user.email 'rblanch@incomm.com'"

# Dumb & Fun
alias parrot='curl parrot.live'
alias weather='curl -4 wttr.in/Atlanta'

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Rubies
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# The Javas
export JAVA_HOME='/Library/Java/Home'
export PATH=${JAVA_HOME}/bin:$PATH
export ANDROID_HOME='/Users/Brice/Library/Android/sdk'
export PATH=${ANDROID_HOME}/tools:$PATH
export PATH=${ANDROID_HOME}/platform-tools:$PATH