#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias v='vim .'
alias dot='~/.dotfiles'
alias desk='~/Desktop'
alias cql='/Users/Shared/apache-cassandra-3.11.3/bin/cqlsh lnc6ed2 -u qacr2db4adm1' -p Mucheasier@1
alias del='rm -rf'
alias cql='cd /Users/Shared/apache-cassandra-3.11.3/bin && ./cqlsh lnc6ed2 -u qacr2db4adm1 -p Mucheasier@1'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"
alias gitown="git config --global github.user 'bricerb' && git config --global user.name 'Brice Blanch' && git config --global user.email 'bricerb@gmail.com'"


# Dumb & Fun
alias parrot='curl parrot.live'
alias weather='curl -4 wttr.in/Atlanta'

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Javas
export JAVA_HOME='/Library/Java/Home'
export PATH=${JAVA_HOME}/bin:$PATH
export GOPATH=/Users/Shared/GolandProjects
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin